{ config, pkgs, ... }:

{
  # Guest integration for this VM. The hardware module generated by NixOS also
  # currently enables virtualisation.virtualbox.guest.enable; keeping this here
  # documents why it is needed for this host.
  virtualisation.virtualbox.guest.enable = true;

  # Shared clipboard/drag-drop are host-side VirtualBox settings; the guest
  # package/service support comes from the option above.
}
