inputs:

{
  config,
  lib,
  pkgs,
  ...
}:

let
  inherit (lib)
    mkEnableOption
    mkOption
    types
    mkIf
    mkDefault
    ;
  cfg = config.programs.illogical-impulse;

  # dotfilesSource = inputs.dotfiles;
  dotfilesSource = "None";

  # Custom packages
  customPkgs = import ./pkgs { inherit pkgs; };
  oneUIIconsPath = "${customPkgs.illogical-impulse-oneui4-icons}/share/icons";
in
{
  options.programs.illogical-impulse.dotfiles = {
    fish.enable = mkEnableOption "Use the Illogical Impulse fish config" // {
      default = true;
    };
    kitty.enable = mkEnableOption "Install kitty and use the Illogical Impulse kitty config" // {
      default = true;
    };
    starship.enable = mkEnableOption "Install starship and use the Illogical Impulse prompt" // {
      default = true;
    };
  };

  options.programs.illogical-impulse.hyprland = {
    plugins = mkOption {
      type = types.listOf types.package;
      default = [ ];
      description = "Hyprland plugins to install and load via hl.plugin()";
    };
  };

  config = mkIf cfg.enable {
    # Shell programs
    programs.fish.enable = cfg.dotfiles.fish.enable;
    programs.starship.enable = cfg.dotfiles.starship.enable;

    # Install plugin .so files into the user environment
    home.packages = cfg.hyprland.plugins;

    # Fake venv at the path upstream expects: ~/.local/state/quickshell/.venv
    # The complex shebang in Python scripts does: source $ILLOGICAL_IMPULSE_VIRTUAL_ENV/bin/activate
    # The upstream env.lua sets ILLOGICAL_IMPULSE_VIRTUAL_ENV to this path.
    home.file = {
      ".local/state/quickshell/.venv/bin/activate".text = ''
        # Generated by illogical-flake - provides the Nix Python env as a fake venv
        export VIRTUAL_ENV="${cfg.internal.pythonEnv}"
        export PATH="${cfg.internal.pythonEnv}/bin:$PATH"
        deactivate() { return 0; }
      '';
      ".local/state/quickshell/.venv/bin/python".source = "${cfg.internal.pythonEnv}/bin/python";
      ".local/state/quickshell/.venv/bin/python3".source = "${cfg.internal.pythonEnv}/bin/python3";
      ".local/state/quickshell/.venv/pyvenv.cfg".text = ''
        home = ${cfg.internal.pythonEnv}/bin
        include-system-site-packages = false
        version = 3.12.0
      '';
    };

    # OneUI icons are copied and modified by the activation script below
    # (cannot use home.file symlinks because we need to modify index.theme)

    # Symlink standard icon themes
    # Note: Papirus themes are handled by activation script (to add inode-directory symlinks)
    # home.file.".local/share/icons/Adwaita".source = "${pkgs.adwaita-icon-theme}/share/icons/Adwaita";
    # hicolor and Papirus are managed by the activation script below, not as symlinks

    # Configure icon theme for GTK and Qt applications
    # Use OneUI-dark which will fall back to Papirus-Dark via inheritance
    gtk = {
      enable = mkDefault true;
      # TODO
      # iconTheme = {
      #   name = mkDefault "OneUI-dark";
      #   package = mkDefault (let
      #     customPkgs = import ./pkgs { inherit pkgs; };
      #   in customPkgs.illogical-impulse-oneui4-icons);
      # };
    };

    # Set icon theme via dconf for GNOME/GTK apps
    dconf.enable = true;
    dconf.settings = {
      "org/gnome/desktop/interface" = {
        # icon-theme = mkDefault "OneUI-dark";
        color-scheme = "prefer-dark";
      };
    };

    # Use activation script to copy files instead of symlinking
    home.activation.copyIllogicalImpulseConfigs = config.lib.dag.entryAfter [ "writeBoundary" ] ''
            # Path to the config directory in the dotfiles source
            # configPath="${dotfilesSource}/dots/.config"
            targetPath="$HOME/.config"

            # Directories to exclude from copying (QuickShell manages these dynamically)
            excludedDirs=("illogical-impulse")

            # # Copy all items from dotfiles .config to user .config
            # $DRY_RUN_CMD mkdir -p "$targetPath"

            # # Create illogical-impulse directory structure if it doesn't exist
            # $DRY_RUN_CMD mkdir -p "$targetPath/illogical-impulse"

            # # Copy the default config.json only if it doesn't already exist
            # if [ ! -f "$targetPath/illogical-impulse/config.json" ]; then
            #   if [ -f "$configPath/illogical-impulse/config.json" ]; then
            #     $DRY_RUN_CMD cp "$configPath/illogical-impulse/config.json" "$targetPath/illogical-impulse/config.json"
            #     $DRY_RUN_CMD chmod u+w "$targetPath/illogical-impulse/config.json"
            #   fi
            # fi

            # for item in "$configPath"/*; do
            #   itemName=$(basename "$item")

            #   # Skip excluded directories
            #   skip=false
            #   for excluded in "''${excludedDirs[@]}"; do
            #     if [ "$itemName" = "$excluded" ]; then
            #       skip=true
            #       break
            #     fi
            #   done

            #   if [ "$skip" = true ]; then
            #     continue
            #   fi

            #   targetItem="$targetPath/$itemName"

            #   # Remove existing file/directory if it exists
            #   if [ -e "$targetItem" ] || [ -L "$targetItem" ]; then
            #     $DRY_RUN_CMD rm -rf "$targetItem"
            #   fi

            #   # Copy the item (works for both files and directories)
            #   $DRY_RUN_CMD cp -r "$item" "$targetItem"

            #   # Make files writable
            #   $DRY_RUN_CMD chmod -R u+w "$targetItem"
            # done

            # echo "Copied Illogical Impulse configuration files to ~/.config"

            # TODO
            # Fix Qt icon theme configuration to use OneUI-dark/OneUI-light with Papirus fallback
            # for qt_conf in "$targetPath/qt5ct/qt5ct.conf" "$targetPath/qt6ct/qt6ct.conf"; do
            #   if [ -f "$qt_conf" ]; then
            #     # Replace OneUI with OneUI-dark, OneUI-light stays as-is
            #     $DRY_RUN_CMD sed -i 's/^icon_theme=OneUI$/icon_theme=OneUI-dark/' "$qt_conf"
            #     $DRY_RUN_CMD sed -i 's/^icon_theme=OneUI-light$/icon_theme=OneUI-light/' "$qt_conf"
            #     echo "Updated Qt icon theme in $(basename $(dirname $qt_conf))"
            #   fi
            # done

            # # Fix fontconfig conf.d if it's a file instead of directory
            # if [ -f "$targetPath/fontconfig/conf.d" ]; then
            #   $DRY_RUN_CMD rm "$targetPath/fontconfig/conf.d"
            #   $DRY_RUN_CMD mkdir -p "$targetPath/fontconfig/conf.d"
            #   echo "Fixed fontconfig/conf.d to be a directory"
            # fi

            # # Copy .local/share contents (icons, etc.)
            # localSharePath="${dotfilesSource}/dots/.local/share"
            targetLocalShare="$HOME/.local/share"

            # if [ -d "$localSharePath" ]; then
            #   $DRY_RUN_CMD mkdir -p "$targetLocalShare"

            #   for item in "$localSharePath"/*; do
            #     if [ -e "$item" ]; then
            #       itemName=$(basename "$item")
            #       targetItem="$targetLocalShare/$itemName"

            #       # Remove existing file/directory if it exists
            #       if [ -e "$targetItem" ] || [ -L "$targetItem" ]; then
            #         $DRY_RUN_CMD rm -rf "$targetItem"
            #       fi

            #       # Copy the item
            #       $DRY_RUN_CMD cp -r "$item" "$targetItem"

            #       # Make files writable
            #       $DRY_RUN_CMD chmod -R u+w "$targetItem"
            #     fi
            #   done

            #   # Move illogical-impulse icon to the correct hicolor theme directory if it exists
            #   if [ -f "$targetLocalShare/icons/illogical-impulse.svg" ]; then
            #     $DRY_RUN_CMD mkdir -p "$targetLocalShare/icons/hicolor/scalable/apps"
            #     $DRY_RUN_CMD mv "$targetLocalShare/icons/illogical-impulse.svg" "$targetLocalShare/icons/hicolor/scalable/apps/"
            #     echo "Moved illogical-impulse icon to hicolor theme directory"
            #   fi

            #   echo "Copied Illogical Impulse .local/share files to ~/.local/share"
            # fi

            # # Copy OneUI icon themes and modify index.theme to inherit from Papirus and Adwaita
            # for theme in OneUI-dark OneUI-light; do
            #   # Use Papirus for primary fallback (has inode-directory), then Adwaita, then hicolor
            #   papirus_theme="Papirus-Dark"
            #   if [ "$theme" = "OneUI-light" ]; then
            #     papirus_theme="Papirus-Light"
            #   fi
            #   fallback_theme="$papirus_theme,Adwaita"

            #   # Remove existing OneUI theme directory
            #   if [ -e "$targetLocalShare/icons/$theme" ] || [ -L "$targetLocalShare/icons/$theme" ]; then
            #     $DRY_RUN_CMD rm -rf "$targetLocalShare/icons/$theme"
            #   fi

            #   # Copy OneUI theme from nix store
            #   oneui_source="${oneUIIconsPath}/$theme"
            #   if [ -d "$oneui_source" ]; then
            #     $DRY_RUN_CMD cp -r "$oneui_source" "$targetLocalShare/icons/$theme"
            #     $DRY_RUN_CMD chmod -R u+w "$targetLocalShare/icons/$theme"

            #     # Update the Inherits line to include Papirus and Adwaita fallbacks
            #     if [ -f "$targetLocalShare/icons/$theme/index.theme" ]; then
            #       $DRY_RUN_CMD sed -i "s/^Inherits=.*/Inherits=$fallback_theme,hicolor/" "$targetLocalShare/icons/$theme/index.theme"
            #       echo "Copied and updated $theme to inherit from $fallback_theme"
            #     fi
            #   fi
            # done

            # # Fix Papirus themes to replace breeze inheritance with Adwaita
            # # Since breeze doesn't have inode-directory icons, we bypass it entirely
            # echo "Fixing Papirus icon inheritance..."
            # for papirus_theme in Papirus-Dark Papirus-Light Papirus; do
            #   papirus_local="$targetLocalShare/icons/$papirus_theme"
            #   papirus_source="${pkgs.papirus-icon-theme}/share/icons/$papirus_theme"

            #   # Always copy from source (removing symlink or directory if exists)
            #   if [ -e "$papirus_local" ] || [ -L "$papirus_local" ]; then
            #     $DRY_RUN_CMD rm -rf "$papirus_local"
            #   fi

            #   if [ -d "$papirus_source" ]; then
            #     $DRY_RUN_CMD cp -r "$papirus_source" "$papirus_local"
            #     $DRY_RUN_CMD chmod -R u+w "$papirus_local"

            #     # Replace breeze inheritance with Adwaita
            #     if [ -f "$papirus_local/index.theme" ]; then
            #       $DRY_RUN_CMD sed -i 's/Inherits=breeze-dark,/Inherits=Adwaita,/g' "$papirus_local/index.theme"
            #       $DRY_RUN_CMD sed -i 's/Inherits=breeze-light,/Inherits=Adwaita,/g' "$papirus_local/index.theme"
            #       $DRY_RUN_CMD sed -i 's/Inherits=breeze,/Inherits=Adwaita,/g' "$papirus_local/index.theme"
            #       echo "Updated $papirus_theme to inherit from Adwaita"
            #     fi

            #     # Papirus already has inode-directory as symlinks, but let's ensure they exist
            #     for size_dir in "$papirus_local"/*/places; do
            #       if [ -d "$size_dir" ] && [ -f "$size_dir/folder.svg" ]; then
            #         if [ ! -e "$size_dir/inode-directory.svg" ]; then
            #           $DRY_RUN_CMD ln -sf folder.svg "$size_dir/inode-directory.svg"
            #           echo "Created inode-directory symlink in $(dirname "$size_dir")/places"
            #         fi
            #       fi
            #     done
            #     echo "Processed $papirus_theme successfully"
            #   fi
            # done

            # Generate NixOS-specific hyprland custom/env.lua
            # This runs AFTER the copy loop, overwriting the empty upstream custom/env.lua.
            # It is sourced by hyprland.lua after hyprland/env.lua, so it can override defaults.
            hyprCustomEnv="$targetPath/hypr/custom/env.lua"
            if [ -d "$targetPath/hypr/custom" ]; then
              cat > "$hyprCustomEnv" << 'LUAEOF'
      -- Generated by illogical-flake. Do not edit manually (regenerated on home-manager switch).
      -- Sourced by hyprland.lua after hyprland/env.lua -- overrides apply to the whole session.
      local home_dir = os.getenv("HOME") or ""
      local user     = os.getenv("USER") or ""

      -- Prepend Nix profile bins so Nix-installed tools are found
      hl.env("PATH",
        home_dir .. "/.nix-profile/bin" ..
        ":/etc/profiles/per-user/" .. user .. "/bin" ..
        ":" .. (os.getenv("PATH") or "/usr/local/bin:/usr/bin:/bin"))

      -- Extend XDG_DATA_DIRS with Nix profile share dirs so desktop files / icons are found
      hl.env("XDG_DATA_DIRS",
        home_dir .. "/.local/share" ..
        ":" .. home_dir .. "/.nix-profile/share" ..
        ":/etc/profiles/per-user/" .. user .. "/share" ..
        ":/run/current-system/sw/share" ..
        ":" .. home_dir .. "/.local/share/flatpak/exports/share" ..
        ":/var/lib/flatpak/exports/share" ..
        ":/usr/local/share:/usr/share")

      -- Use qt6ct (available in Nix profile) instead of upstream "kde"
      hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
      LUAEOF
              chmod u+w "$hyprCustomEnv"
              echo "Generated hyprland custom/env.lua with NixOS paths"
            fi

            # Generate custom/general.lua with declarative plugin loading
            hyprCustomGeneral="$targetPath/hypr/custom/general.lua"
            if [ -d "$targetPath/hypr/custom" ]; then
              # Append plugin calls to whatever the upstream default general.lua has
              cat >> "$hyprCustomGeneral" << 'LUAEOF'

      -- Hyprland plugins loaded by illogical-flake
      ${
        lib.concatMapStrings (plugin: ''
          hl.plugin("${plugin}/lib/lib${plugin.pname}.so")
        '') cfg.hyprland.plugins
      }LUAEOF
              chmod u+w "$hyprCustomGeneral"
              echo "Generated hyprland custom/general.lua plugin entries"
            fi

            # TODO
            # Update icon cache for all installed icon themes
            # echo "Updating icon cache..."
            # for theme_dir in "$targetLocalShare/icons"/*; do
            #   if [ -d "$theme_dir" ]; then
            #     theme_name=$(basename "$theme_dir")
            #     if [ -f "$theme_dir/index.theme" ] || [ -f "$theme_dir/icon-theme.cache" ]; then
            #       $DRY_RUN_CMD ${pkgs.gtk3}/bin/gtk-update-icon-cache -f -t "$theme_dir" 2>/dev/null || true
            #       echo "Updated icon cache for $theme_name"
            #     fi
            #   fi
            # done
    '';
  };
}
