-- Generated by illogical-flake. Do not edit manually (regenerated on home-manager switch).
-- Sourced by hyprland.lua after hyprland/env.lua -- overrides apply to the whole session.
local home_dir = os.getenv("HOME") or ""
local user     = os.getenv("USER") or ""

-- Prepend Nix profile bins so Nix-installed tools are found
hl.env("PATH",
  home_dir .. "/.nix-profile/bin" ..
  ":/etc/profiles/per-user/" .. user .. "/bin" ..
  ":" .. (os.getenv("PATH") or "/usr/local/bin:/usr/bin:/bin"))

-- Extend XDG_DATA_DIRS with Nix profile share dirs so desktop files / icons are found
hl.env("XDG_DATA_DIRS",
  home_dir .. "/.local/share" ..
  ":" .. home_dir .. "/.nix-profile/share" ..
  ":/etc/profiles/per-user/" .. user .. "/share" ..
  ":/run/current-system/sw/share" ..
  ":" .. home_dir .. "/.local/share/flatpak/exports/share" ..
  ":/var/lib/flatpak/exports/share" ..
  ":/usr/local/share:/usr/share")

-- Use qt6ct (available in Nix profile) instead of upstream "kde"
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
